### ISSUE TITLE
Overhaul screensavers

### ISSUE THREAD

**Issue by SeanPM5** [SeanPM5/homeassistant-config#18]
Screensavers that would play on living room TV used to use an input_select. I am migrating them to be conditional buttons instead, so I guess they'd be switches. Would have the additional benefit of voice control (ie "Hey Google, turn on living room aquarium screensaver").

**Comment by SeanPM5** [comment]
Considering creating a decluttering-card template instead, would make the code a lot cleaner and easier to update. Something along the lines of this.

```
- type: custom:decluttering-card
  template: screensaver
  variables:
    - name: Aquarium
    - icon: mdi:fish
    - screensaver: https://www.youtube.com/watch?v=XVkADAwOXnU
    - sound: yes
```

This would make other things more difficult though - voice controls, companion lighting scenes, and most importantly being able to see the state for use in other automations. I want to know whether a screensaver is active or not.
