### ISSUE TITLE
Fix custom_updater notification

### ISSUE THREAD

**Issue by SeanPM5** [SeanPM5/homeassistant-config#40]
Am trying to add version numbers (available and installed) to my custom_updater notification. Seems beyond my abilities though.

This is the code for notification:
```
      data_template:
        title: "{{ trigger.to_state.attributes.domain }} Update Available"
        message: "An updated version of {{ trigger.to_state.attributes.has_update[-1] }} is available. (Version {{ trigger.to_state.attributes.remote }}, you have {{ trigger.to_state.attributes.local }})."
        data:
          url: "{{ trigger.to_state.attributes.change_log }} "
```

and here's how it displays:

![image](https://i.imgur.com/ODNIngS.jpg)

```
domain: custom_cards
has_update: button-card,radial-menu
button-card: {
  "local": "0.0.7",
  "remote": "0.0.8",
  "has_update": true,
  "not_local": false,
  "repo": "https://github.com/custom-cards/button-card",
  "change_log": "https://github.com/custom-cards/button-card"
}
radial-menu: {
  "local": "1.0.0",
  "remote": "1.0.1",
  "has_update": true,
  "not_local": false,
  "repo": "https://github.com/custom-cards/radial-menu",
  "change_log": "https://github.com/custom-cards/radial-menu"
}
```
I think that it's looking for a top-level attribute "remote" rather than inside the actual items. I'm not sure how to drill down deeper, probably easy but I've spent a lot of time on this and am stumped.
