### ISSUE TITLE
hold_action on custom button-card

### ISSUE THREAD

**Issue by SeanPM5** [SeanPM5/homeassistant-config#45]
Long press support (hold_action) is being added to custom button card. Which means more goodies to play with. 

```
- type: "custom:button-card"
  entity: switch.skylight
  name: more-info
  hold_action:
    action: more-info
```

Update my UI and come up with ideas here so I'll be ready to take advantage of them right away.

## Checklist:
- [x] Long press Sleep Status tab to manually start bedtime routine
- [x] Long press Daily Stats tab to swap infos to Weekly Stats (make sure icon updates too)
- [x] For links section add long press to change links. Ie a Home Assitant webpage link, long press to go specifically to release notes. HA Polymer GitHub long press would go to HA Ui-Schema GitHub. etc.
- [ ] Update Available button - tap_action brings to hassio dashboard page, hold_action runs update script
- [ ] Lights - tap action toggle hold_action more info ? Or hold_action brings up a conditional view with certain scenes etc. Could think of some cool things with this.
