### ISSUE TITLE
Move iPhone to a notify group

### ISSUE THREAD

**Issue by SeanPM5** [SeanPM5/homeassistant-config#7]
I should add my iPhone to a [Notify Group](https://www.home-assistant.io/components/notify.group/) with just my phone in it, that way the entity_id will never change when I upgrade phones, and my automations won't have to be updated after every yearly upgrade etc. I'd be able to just update the entity_id in the notify group instead of dozens of different places.

It'll just always be `notify.sean_phone` which looks cleaner as well.

config to use:
```
  - name: sean_phone
    platform: group
    services:
      - service: ios_seans_iphone_xs
```
